# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  log-level:
    description: |
      Trino server logging level. 
      Valid values: info, debug, warn, error.
    default: info
    type: string
  int-comms-secret:
    description: |
      The secret Trino uses to communicate between nodes.
    type: string
  https-enabled:
    description: | 
      To enable HTTPS secure communication protocol.
      google-client-id and google-client-secret must also be provided.
      A relation with the tls-certificates-operator must also be in place.
    type: boolean
    default: False
  google-client-id:
    description: |
      Client id from Google Oauth setup
    type: string
  google-client-secret:
    description: |
      Client password from Google Oauth setup
    type: string
  ranger-acl:
    description: |
      Enabling/disabling Ranger plugin for Trino
    default: False
    type: boolean
  policy-mgr-url:
    description: |
      Ranger URL for policy management
    default: "http:ranger-admin:6080"
    type: string
  ranger-version:
    description: |
      Version of Ranger for Trino plugin
    default: "2.3.0"
    type: string