# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  log-level:
    description: |
      Trino server logging level. 
      Valid values: info, debug, warn, error.
    default: info
    type: string
  int-comms-secret:
    description: |
      The secret Trino uses to communicate between nodes.
    type: string
  google-client-id:
    description: |
      Client id from Google Oauth setup
    type: string
  google-client-secret:
    description: |
      Client password from Google Oauth setup
    type: string
  web-proxy:
    description: |
      The address of the web proxy. To be used in combination
      with google-client-id and google-client-secret values.
    type: string 
  ranger-service-name:
    description: |
      The service name for Trino in Apache Ranger when related. Defaults to relation id.
    type: string
  external-hostname:
    description: |
        The DNS listing used for external connections. 
        Will default to the name of the deployed application.
    type: string
    default: trino-k8s
  tls-secret-name:
    description: |
        Name of the k8s secret which contains the TLS certificate to be used by ingress.
    default: "trino-tls"
    type: string
  charm-function:
    description: |
      One of `coordinator`, `worker` or `all` to determine the function of the application.
      `all` will result in a single node deployment, not recommended for production.
    default: coordinator
    type: string
  discovery-uri:
    description: |
        When using a coordinator and worker this is the host and port of the 
        coordinator service that the workers announce themselves to.
    type: string
    default: http://trino-k8s:8080
  catalog-config:
    description: |
      Catalogs for which Trino should be connected.
    type: string
  oauth-user-mapping:
    description: |
      Optional regex pattern with capture group to determine the username from oauth email.
      ie. (.*)@.*
    type: string
  acl-mode-default:
    description: |
      The default ACLs for all Trino catalogs, one of `all` or `none`.
      `all`: Allow all users access to all catalogs.
      `none`: Deny all users access to all catalogs.
      A Ranger relation will supersede this default.
    type: string
    default: all
  acl-user-pattern:
    description: |
      The pattern to match users, for which the policy should be applied.
      The default value `.*` applies to all users.
    type: string
    default: .*
  acl-catalog-pattern:
    description: |
      The pattern to match catalog names, for which the policy should be applied.
      The default value `.*` applies to all catalogs.
    type: string
    default: .*
  user-secret-id:
    description: |
      The Juju secret id for the Trino user credentials.
    type: string
  additional-jvm-options:
    description: |
      Space-separated string of JVM options to be added to the config file.
      By default the following options are included. 
      The value of the option can be overwritten by providing the option 
      with the updated value via this config parameter.
        "-Xmx2G"
        "-XX:InitialRAMPercentage=80"
        "-XX:+ExplicitGCInvokesConcurrent"
        "-XX:-OmitStackTraceInFastThrow"
        "-Djdk.attach.allowAttachSelf=true"
        "-Dfile.encoding=UTF-8"
        "-XX:+ExitOnOutOfMemoryError",
        "-XX:+HeapDumpOnOutOfMemoryError",
    type: string
  coordinator-request-timeout:
    description: |
      Specifies the maximum amount of time the client will wait for a response from
      the coordinator once a connection has been established. This timeout ensures
      that client requests do not stall indefinitely if the coordinator is slow to
      respond.
    type: string
    default: "10m"
  coordinator-connect-timeout:
    description: |
      Specifies the maximum amount of time the client will wait for a connection
      to be established with the coordinator. If the connection cannot be made within
      this period, the client will give up and raise an error.
    type: string
    default: "30s"
  worker-request-timeout:
    description: |
      Specifies the maximum amount of time the coordinator will wait for a response
      from a worker node after the connection is established. This setting helps
      manage scenarios where worker nodes are slow to respond, ensuring that
      the coordinator does not wait indefinitely.
    type: string
    default: "30s"
  max-concurrent-queries:
    description: |
      The maximum number of queries that Trino is allowed to run concurrently.
      Any additional queries beyond this limit will be queued until a running query
      finishes.
    type: int
    default: 5
  workload-memory-requests:
    description: |
      Kubernetes memory resource request for the trino workload container.
      eg. "1Gi"
    type: string
  workload-memory-limits:
    description: |
      Kubernetes memory resource request for the trino workload container.
      This should be equal to or greater than your requests.
      eg. "1Gi"
    type: string
  workload-cpu-requests:
    description: |
      Kubernetes cpu resource request for the trino workload container.
      eg. 1
    type: string
  workload-cpu-limits:
    description: |
      Kubernetes cpu resource request for the trino workload container.
      This should be equal to or greater than your requests.
      eg. 1
    type: string
