# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  log-level:
    description: |
      Trino server logging level. 
      Valid values: info, debug, warn, error.
    default: info
    type: string
  int-comms-secret:
    description: |
      The secret Trino uses to communicate between nodes.
    type: string
  google-client-id:
    description: |
      Client id from Google Oauth setup
    type: string
  google-client-secret:
    description: |
      Client password from Google Oauth setup
    type: string
  web-proxy:
    description: |
      The address of the web proxy. To be used in combination
      with google-client-id and google-client-secret values.
    type: string 
  ranger-service-name:
    description: |
      The service name for Trino in Apache Ranger when related. Defaults to relation id.
    type: string
  external-hostname:
    description: |
        The DNS listing used for external connections. 
        Will default to the name of the deployed application.
    type: string
    default: trino-k8s
  tls-secret-name:
    description: |
        Name of the k8s secret which contains the TLS certificate to be used by ingress.
    default: "trino-tls"
    type: string
  charm-function:
    description: |
      One of `coordinator`, `worker` or `all` to determine the function of the application.
      `all` will result in a single node deployment, not recommended for production.
    default: coordinator
    type: string
  discovery-uri:
    description: |
        When using a coordinator and worker this is the host and port of the 
        coordinator service that the workers announce themselves to.
    type: string
    default: http://trino-k8s:8080
  catalog-config:
    description: |
      Catalogs for which Trino should be connected.
    type: string
  oauth-user-mapping:
    description: |
      Optional regex pattern with capture group to determine the username from oauth email.
      ie. (.*)@.*
    type: string
  acl-mode-default:
    description: |
      The default ACLs for all Trino catalogs, one of `all` or `none`.
      `all`: Allow all users access to all catalogs.
      `none`: Deny all users access to all catalogs.
      A Ranger relation will supersede this default.
    type: string
    default: all
  acl-user-pattern:
    description: |
      The pattern to match users, for which the policy should be applied.
      The default value `.*` applies to all users.
    type: string
    default: .*
  acl-catalog-pattern:
    description: |
      The pattern to match catalog names, for which the policy should be applied.
      The default value `.*` applies to all catalogs.
    type: string
    default: .*
  user-secret-id:
    description: |
      The Juju secret id for the Trino user credentials.
    type: string
  xmx-size:
    description: |
      Maximum heap size for the JVM.
    type: string
    default: '2G'
  initial-ram-percentage:
    description: |
      Percentage of total RAM to be allocated as initial heap size.
    type: int
    default: 80
  max-ram-percentage:
    description: |
      Maximum percentage of total RAM to be used by the JVM.
    type: int
    default: 80
  heap-region-size:
    description: |
      Size of each heap region for the JVM's garbage collector.
    type: string
    default: '32M'
  reserved-cache-size:
    description: |
      Amount of memory reserved for the JVM's code cache.
    type: string
    default: '512M'
  retry-allocation-count:
    description: |
      Number of times to retry memory allocation during GC.
    type: int
    default: 32
  additional-jvm-options:
    description: |
      Space separated string of JVM options to be added to the config file.
      If no value if provided then the following are included by default:
        -XX:+ExplicitGCInvokesConcurrent
        -XX:+ExitOnOutOfMemoryError
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:-OmitStackTraceInFastThrow
        -XX:PerMethodRecompilationCutoff=10000
        -XX:PerBytecodeRecompilationCutoff=10000
        -Djdk.attach.allowAttachSelf=true
        -Djdk.nio.maxCachedBufferSize=2000000
        -Dfile.encoding=UTF-8
        -XX:+EnableDynamicAgentLoading
    type: string
