# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  log-level:
    description: |
      Trino server logging level. 
      Valid values: info, debug, warn, error.
    default: info
    type: string
  int-comms-secret:
    description: |
      The secret Trino uses to communicate between nodes.
    type: string
  google-client-id:
    description: |
      Client id from Google Oauth setup
    type: string
  google-client-secret:
    description: |
      Client password from Google Oauth setup
    type: string
  web-proxy:
    description: |
      The address of the web proxy. To be used in combination
      with google-client-id and google-client-secret values.
    type: string 
  ranger-acl-enabled:
    description: |
      Enabling/disabling Ranger plugin for Trino
    default: False
    type: boolean
  policy-mgr-url:
    description: |
      Ranger URL for policy management
    default: "http:ranger-admin:6080"
    type: string
  ranger-version:
    description: |
      Version of Ranger for Trino plugin
    default: "2.3.0"
    type: string
  external-hostname:
    description: |
        The DNS listing used for external connections. 
        Will default to the name of the deployed application.
    type: string
    default: trino-k8s
  tls-secret-name:
    description: |
        Name of the k8s secret which contains the TLS certificate to be used by ingress.
    default: "trino-tls"
    type: string
  trino-password:
    description: |
        Password to be used for default trino user created on startup.
    default: ubuntu123
    type: string
  charm-function:
    description: |
      One of coordinator or worker, to determine function of the application
    default: coordinator
    type: string
