# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
#
# Learn more about testing at: https://juju.is/docs/sdk/testing


"""Trino policy unit tests."""

# pylint:disable=protected-access

import logging
from unittest import TestCase

from ops.testing import Harness
from unit.helpers import (
    POLICY_MGR_URL,
    RANGER_LIB,
    RANGER_PROPERTIES_PATH,
    TEST_CATALOG_CONFIG,
)

from charm import TrinoK8SCharm

logger = logging.getLogger(__name__)


class TestPolicy(TestCase):
    """Unit tests.

    Attrs:
        maxDiff: Specifies max difference shown by failed tests.
    """

    maxDiff = None

    def setUp(self):
        """Set up for the unit tests."""
        self.harness = Harness(TrinoK8SCharm)
        self.addCleanup(self.harness.cleanup)
        self.harness.set_can_connect("trino", True)
        self.harness.set_leader(True)
        self.harness.set_model_name("trino-model")
        self.harness.add_network("10.0.0.10", endpoint="peer")
        self.harness.begin()

    def test_policy_relation_created(self):
        """Add policy relation."""
        harness = self.harness
        simulate_lifecycle(harness)

        rel_id = harness.add_relation("policy", "trino-k8s")
        harness.add_relation_unit(rel_id, "trino-k8s/0")

        data = {self.harness.charm.app: {}}
        event = make_relation_event("ranger-k8s", rel_id, data)
        harness.charm.policy._on_relation_created(event)

        relation_data = self.harness.get_relation_data(rel_id, "trino-k8s")
        assert relation_data == {
            "name": f"relation_{rel_id}",
            "type": "trino",
            "jdbc.driverClassName": "io.trino.jdbc.TrinoDriver",
            "jdbc.url": "jdbc:trino://trino-k8s:8080",
        }

    def test_policy_relation_changed(self):
        """Add policy_manager_url to the relation databag."""
        harness = self.harness
        simulate_lifecycle(harness)
        container = harness.model.unit.get_container("trino")

        # Create the relation
        rel_id = harness.add_relation("policy", "trino-k8s")
        harness.add_relation_unit(rel_id, "trino-k8s/0")
        harness.handle_exec("trino", ["bash"], result=0)

        # Create and emit the policy `_on_relation_changed` event.
        data = {
            "ranger-k8s": {
                "policy_manager_url": POLICY_MGR_URL,
            },
        }
        event = make_relation_event("ranger-k8s", rel_id, data)
        harness.charm.policy._on_relation_changed(event)

        self.assertTrue(container.exists(RANGER_PROPERTIES_PATH))

    def test_policy_relation_broken(self):
        """Add policy_manager_url to the relation databag."""
        harness = self.harness
        simulate_lifecycle(harness)

        rel_id = harness.add_relation("policy", "trino-k8s")
        harness.add_relation_unit(rel_id, "trino-k8s/0")
        harness.handle_exec("trino", ["bash"], result=0)

        data = {"ranger-k8s": {}}
        event = make_relation_event("ranger-k8s", rel_id, data)
        harness.charm.policy._on_relation_broken(event)

        self.assertFalse(
            event.relation.data["ranger-k8s"].get("user-group-configuration")
        )

    def test_restore_ranger_plugin(self):
        """Restore plugin if lost."""
        harness = self.harness
        self.test_policy_relation_changed()
        container = harness.model.unit.get_container("trino")
        container.remove_path(RANGER_LIB, recursive=True)
        harness.charm.on.trino_pebble_ready.emit(container)
        assert container.exists(RANGER_LIB)


def simulate_lifecycle(harness):
    """Simulate a healthy charm life-cycle.

    Args:
        harness: ops.testing.Harness object used to simulate charm lifecycle.
    """
    # Simulate peer relation readiness.
    harness.add_relation("peer", "trino")

    # Simulate pebble readiness.
    container = harness.model.unit.get_container("trino")
    harness.charm.on.trino_pebble_ready.emit(container)

    # Add worker and coordinator relation
    harness.update_config({"catalog-config": TEST_CATALOG_CONFIG})
    harness.add_relation("trino-coordinator", "trino-k8s-worker")


def make_relation_event(app, rel_id, data):
    """Create and return a mock policy created event.

        The event is generated by the relation with postgresql_db

    Args:
        app: name of the application.
        rel_id: relation id.
        data: relation data.

    Returns:
        Event dict.
    """
    return type(
        "Event",
        (),
        {
            "app": app,
            "relation": type(
                "Relation",
                (),
                {
                    "data": data,
                    "id": rel_id,
                },
            ),
        },
    )
