name: Publish to edge

on:
  push:
    branches:
      - main

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/test_and_publish_charm.yaml@6e6117fd572a865957063d78ea4ac8827d2bd06d
    secrets: inherit
    with:
      integration-test-provider: microk8s
      integration-test-provider-channel: 1.25-strict/stable
      integration-test-juju-channel: 3.1/stable
      integration-test-modules: '["test_charm"]'
